x-test-runner-build: &test-runner-build
  context: ../..
  dockerfile: docker/norfab-docker-tests/Dockerfile.norfab.test-runner
  args:
    PYTHON_VERSION: ${PYTHON_VERSION:-3.12}

x-test-runner-env: &test-runner-env
  PYTHONPATH: /workspace

x-test-runner-entrypoint: &test-runner-entrypoint
  - python
  - -c
  - |
    import os
    import sys

    os.chdir("/workspace/tests")

    args = [arg[6:] if arg.startswith("tests/") else arg for arg in sys.argv[1:]]
    os.execvp(
        "python",
        [
            "python",
            "-m",
            "pytest",
            "-vv",
            "-c",
            "/workspace/pyproject.toml",
            "-o",
            "cache_dir=/tmp/pytest-cache",
            f"--junitxml={os.environ['PYTEST_JUNIT_XML']}",
        ]
        + args,
    )

x-workspace-volume: &workspace-volume
  type: bind
  source: ../..
  target: /workspace
  read_only: true

x-inventory-volume: &inventory-volume
  type: bind
  source: ../../tests/nf_tests_inventory
  target: /workspace/tests/nf_tests_inventory
  read_only: false

x-test-runner-common: &test-runner-common
  build: *test-runner-build
  working_dir: /workspace/tests
  entrypoint: *test-runner-entrypoint

services:
  core-tests:
    <<: *test-runner-common
    image: norfab:core-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./core-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/core-junit.xml
    command:
      - -m
      - core
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./core-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  nornir-service-tests:
    <<: *test-runner-common
    image: norfab:nornir-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./nornir-service-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/nornir-service-junit.xml
    command:
      - -m
      - nornir
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./nornir-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  netbox-service-tests:
    <<: *test-runner-common
    image: norfab:netbox-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./netbox-service-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/netbox-service-junit.xml
    command:
      - -m
      - netbox
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./netbox-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  fakenos-service-tests:
    <<: *test-runner-common
    image: norfab:fakenos-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./fakenos-service-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/fakenos-service-junit.xml
    command:
      - -m
      - fakenos
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./fakenos-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  containerlab-service-tests:
    <<: *test-runner-common
    image: norfab:containerlab-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./containerlab-service-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/containerlab-service-junit.xml
    command:
      - -m
      - containerlab
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./containerlab-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  workflow-service-tests:
    <<: *test-runner-common
    image: norfab:workflow-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./workflow-service-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/workflow-service-junit.xml
    command:
      - -m
      - workflow
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./workflow-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  agent-tests:
    <<: *test-runner-common
    image: norfab:agent-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./agent-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/agent-junit.xml
    command:
      - -m
      - clientagent
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./agent-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  fastmcp-service-tests:
    <<: *test-runner-common
    image: norfab:fastmcp-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./fastmcp-service-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/fastmcp-service-junit.xml
    command:
      - -m
      - fastmcp
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./fastmcp-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  fastapi-service-tests:
    <<: *test-runner-common
    image: norfab:fastapi-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./fastapi-service-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/fastapi-service-junit.xml
    command:
      - -m
      - fastapi
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./fastapi-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  filesharing-service-tests:
    <<: *test-runner-common
    image: norfab:filesharing-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./nornir-service-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/filesharing-service-junit.xml
    command:
      - -m
      - filesharing
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./filesharing-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  dummy-service-tests:
    <<: *test-runner-common
    image: norfab:dummy-service-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./core-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/dummy-service-junit.xml
    command:
      - -m
      - dummy
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./dummy-service-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__

  nfcli-tests:
    <<: *test-runner-common
    image: norfab:nfcli-tests-py${PYTHON_VERSION:-3.12}
    env_file:
      - ./core-tests/.env
    environment:
      <<: *test-runner-env
      PYTEST_JUNIT_XML: /workspace/tests/nf_tests_inventory/__norfab__/artifacts/nfcli-junit.xml
    command:
      - -m
      - nfcli
    volumes:
      - *workspace-volume
      - *inventory-volume
      - type: bind
        source: ./nfcli-tests/__norfab__
        target: /workspace/tests/nf_tests_inventory/__norfab__
