FROM python:3.9.7-slim-bullseye

RUN apt-get update && \
    apt-get install --no-install-recommends -y openssh-client && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade

COPY norfab/ /tmp/norfab/

RUN pip install --no-cache-dir /tmp/norfab/.[nornirservice] --upgrade && \
    pip install --no-cache-dir /tmp/norfab/.[nfcli] --upgrade 

ENV LOG_LEVEL=INFO

ENTRYPOINT cd /etc/norfab/ && nfcli --workers-list nornir-worker-1 -l $LOG_LEVEL