services:
  norfab:
    container_name: norfab-dev
    hostname: norfab-dev
    image: norfab:aio-dev
    build:
      context: ../../
      dockerfile: docker/norfab-docker-build/Dockerfile.norfab.aio
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    init: true
    env_file:
      - ./.env
    volumes:
      # Bind the development inventory and runtime files.
      - type: bind
        source: ./norfab/
        target: /etc/norfab/
      # Override the installed package with the local working tree.
      - type: bind
        source: ../../norfab/
        target: /usr/local/lib/python${PYTHON_VERSION}/site-packages/norfab/
    networks:
      net0:
        ipv4_address: 10.0.0.100
    ports:
      - "5555:5555/tcp"
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "9005:9005/tcp"

networks:
  net0:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
