version: "3.9"

services:

  norfab-broker:
    container_name: "norfab-broker"
    hostname: 'norfab-broker'
    build:
      context: ../../../
      dockerfile: norfab/docker/norfab-docker-dev/Dockerfile.norfab.broker
    environment:
      LOG_LEVEL: INFO
    volumes:
      # bind folder with norfab files
      - type: bind
        source: ./norfab/
        target: /etc/norfab/
      # bind NorFab packages for development
      - type: bind
        source: ../../norfab/
        target: /usr/local/lib/python3.9/site-packages/norfab/
    networks:
      net0:
        ipv4_address: 10.0.0.100
    # expose ZeroMQ port
    ports:
      - "5555:5555/tcp"
        
  norfab-service-nornir:
    container_name: "norfab-service-nornir"
    hostname: 'norfab-service-nornir'
    build:
      context: ../../../
      dockerfile: norfab/docker/norfab-docker-dev/Dockerfile.norfab.nornir
    environment:
      LOG_LEVEL: INFO
    volumes:
      # bind folder with norfab files
      - type: bind
        source: ./norfab/
        target: /etc/norfab/
      # bind NorFab packages for development
      - type: bind
        source: ../../norfab/
        target: /usr/local/lib/python3.9/site-packages/norfab/
    networks:
      net0:
        ipv4_address: 10.0.0.101
    depends_on:
      - norfab-broker

  norfab-service-netbox:
    container_name: "norfab-service-netbox"
    hostname: 'norfab-service-netbox'
    build:
      context: ../../../
      dockerfile: norfab/docker/norfab-docker-dev/Dockerfile.norfab.netbox
    environment:
      LOG_LEVEL: INFO
    volumes:
      # bind folder with norfab files
      - type: bind
        source: ./norfab/
        target: /etc/norfab/
      # bind NorFab packages for development
      - type: bind
        source: ../../norfab/
        target: /usr/local/lib/python3.9/site-packages/norfab/
    networks:
      net0:
        ipv4_address: 10.0.0.102
    depends_on:
      - norfab-broker

networks:
  net0:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1