version: "3.9"

services:

  norfab:
    container_name: "norfab"
    hostname: 'norfab'
    image: docker.io/dmulyalin/norfab:aio-latest
    environment:
      LOG_LEVEL: INFO
    volumes:
      - type: bind
        source: ./norfab/
        target: /etc/norfab/
