ARG PYTHON_VERSION=3.12

FROM python:${PYTHON_VERSION}-slim-trixie

RUN apt-get update && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade

RUN pip install --no-cache-dir norfab --upgrade

ENV TERMINAL_LOGGING_LEVEL=INFO

ENTRYPOINT cd /etc/norfab/ && nfcli -b -l $TERMINAL_LOGGING_LEVEL