FROM python:3.10-slim-trixie

RUN apt-get update && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade

RUN pip install --no-cache-dir norfab --upgrade && \
    pip install --no-cache-dir norfab[fastapiservice] --upgrade

ENV LOG_LEVEL=INFO
ENV WORKERS_LIST=

ENTRYPOINT cd /etc/norfab/ && nfcli --workers-list $WORKERS_LIST -l $LOG_LEVEL