FROM python:3.11-slim-trixie

RUN apt-get update && \
    apt-get install --no-install-recommends -y openssh-client procps && \
    apt-get clean && \
    pip install --no-cache-dir pip setuptools wheel poetry --upgrade

RUN pip install --no-cache-dir norfab --upgrade && \
    pip install --no-cache-dir norfab[full]

ENV LOG_LEVEL=INFO

ENTRYPOINT cd /etc/norfab/ && nfcli -w -b -l $LOG_LEVEL